import "./globals.css";
import MainApp from "./mainApp";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props) {
  return (
    <html lang="en">
      <body>
        <MainApp >{props.children}</MainApp>
      </body>
    </html>
  );
}
